[package]
authors = ["Tangram <root@tangram.dev"]
description = "Tangram makes it easy for programmers to train, deploy, and monitor machine learning models."
documentation = "https://docs.rs/tangram"
edition = "2021"
rust-version = "1.56"
homepage = "https://github.com/tangramdotdev/tangram"
license = "MIT"
name = "tangram_table"
publish = true
repository = "https://github.com/tangramdotdev/tangram"
version = "0.7.0"

[lib]
path = "lib.rs"

[dev-dependencies]
insta = "1"
tempfile = "3"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
csv = "1"
hdf5 = {version = "0.8", optional = true }
fast-float = "0.2"
fnv = "1"
ndarray = { version = "0.15", features = ["rayon"] }
num = "0.4"
tangram_progress_counter = { version = "0.7.0", path = "../progress_counter" }
tangram_zip = { version = "0.7.0", path = "../zip" }
